name: Draw ZMK Keymaps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Draw keymaps
        uses: caksoylar/keymap-drawer@v1.6.1
        with:
          config_path: config/keymap_drawer.yaml
          keymap_path: config/corne.keymap
          output_folder: keymap-drawer

      - name: Commit drawings
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update keymap drawings"
          file_pattern: "keymap-drawer/*.svg"